name: Production deployment
on:
  push:
    branches: ['main']

jobs:
  build-blockscout:
    uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment.yml@main
    with:
      ingressEnabled: "yes"
      ingressHost: "blockscout.prod.astranet.services"
      replicas: "2"
      kafkaCert: "true"
      kafkaEnv: "prod"
      servicePort: "4000"
    secrets: inherit
  build-blockscout-worker:
    uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment.yml@main
    with:
      workloadName: blockscout-worker-prod
      replicas: "1"
      kafkaCert: "true"
      kafkaEnv: "prod"
    secrets: inherit